### PR TITLE
README example: transport.Transport -> transport.solve

### PR DESCRIPTION
**Pull request by bamos**
Otherwise this gives the error:

```
Traceback (most recent call last):
  File "./t.py", line 17, in <module>
    ot = transport.Transport(x, y, a=a, b=b)
TypeError: __new__() got an unexpected keyword argument 'a'
```

### CODE REVIEW

**Comment by bamos** [comment]
Also using the master branch gives me this error (but everything is working well in `0.2.2`):

```
Traceback (most recent call last):
  File "./t.py", line 17, in <module>
    ot = transport.solve(x, y, a=a, b=b)
  File "/home/bda/src/ott/ott/tools/transport.py", line 121, in solve
    output = solver(pb)
  File "/home/bda/src/ott/ott/core/sinkhorn.py", line 384, in __call__
    return run_fn(ot_prob, self, (init_dual_a, init_dual_b))
  File "/home/bda/src/ott/ott/core/sinkhorn.py", line 521, in run
    out = iter_fun(ot_prob, solver, init)
  File "/home/bda/src/ott/ott/geometry/pointcloud.py", line 270, in tree_flatten
    return ((self.x, self.y, self._epsilon, self._cost_fn),
  File "/home/bda/src/ott/ott/geometry/geometry.py", line 108, in _epsilon
    return epsilon_scheduler.Epsilon.make(eps, scale=self.scale, **self._kwargs)
  File "/home/bda/src/ott/ott/geometry/epsilon_scheduler.py", line 92, in make
    return cls(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'fused_penalty'
```

**Comment by marcocuturi** [comment]
Thanks Brandon! We'll investigate the fused_penalty bug.
